$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - node_modules
  - bun.lockb
  - ./branch_out
  - .tsbuildinfo
  - .gitignore
  - dist
  - storybook-static
  - .next
  - .astro
  - drizzle
  - migrations
  - '**/*.yml'
  - '**/*.svg'
words:
  - biomejs
  - biome
  - acst
  - tsparticles
  - fuzzie
  - CLIENTVAR
  - hono
  - MAILBRIDGE
  - simplewebauthn
  - itty
  - unstorage
  - unsession
  - totp
  - RPID
  - Uninbox
  - Segoe
  - Roboto
  - Neue
  - Noto
  - htpasswd
  - domainkey
  - autoconfig
  - autodiscover
  - broadcasthost
  - chacha
  - chiefexecutiveofficer
  - cpanel
  - crossdomain
  - diffie
  - domainname
  - nistp
  - forgotpassword
  - muckrat
  - hostedzone
  - QBWIKFIG
  - CHANNELLOG
  - callout
  - vercel
  - tiktok
  - supabase
  - stackoverflow
  - snapcraft
  - haskel
  - flyio
  - vuejs
  - webflow
  - yourname
  - yourusername
  - webbot
  - webmail
  - umac
  - unboarding
  - unfollow
  - unproprietar
  - unproprietarycorporation
  - mailerdaemon
  - poweruser
  - publicrelations
  - rebortbot
  - unproprietary
  - uucp
  - vicepresident
  - webadmin
  - wpad
  - flatpak
  - rootuser
  - ssladmin
  - ssladministrator
  - sslwebmaster
  - supportbot
  - ticketbot
  - humanresources
  - isatap
  - keybase
  - localdomain
  - Editrix
  - Algochurn
  - SAMEORIGIN
  - elpresidank
  - authprovider
  - nosniff
  - SEMRESATTRS
  - Aceternity
  - Renderwork
  - svgr
  - infobar
  - Bois
  - bois
  - goup
  - Fuzzie
  - fuzzie
  - lefthook
  - dbaeumer
  - applicaiton
  - subrouters
  - unauthed
  - CBFF
  - automations
  - aest
  - akst
  - astro
  - astrojs
  - autodocs
  - autoplay
  - awst
  - Beamer
  - Binni
  - branchname
  - bunx
  - bvaughn
  - Byrom
  - callees
  - classname
  - clsx
  - cmdk
  - codespace
  - codespaces
  - Colm
  - commitlint
  - commitlintrc
  - compat
  - consts
  - crossorigin
  - Bios
  - convo
  - convos
  - Ilike
  - ilike
  - planetscale
  - infisical
  - varchar
  - autoincrement
  - warhawk
  - datetime
  - degit
  - Duarte
  - Elsakaan
  - Embla
  - esbenp
  - hookform
  - ianvs
  - codedank
  - jiti
  - lockb
  - lucide
  - Malyavko
  - Mintlify
  - neonctl
  - neondatabase
  - nextjs
  - nzst
  - yeebois
  - Ornella
  - packagejson
  - pacocoursey
  - peduarte
  - quickstart
  - Ratelimit
  - shadcn
  - sslmode
  - starterkit
  - starterkits
  - stylesheet
  - superjson
  - tada
  - tailwindcss
  - tanstack
  - thollander
  - todos
  - topbar
  - trpc
  - tsbuildinfo
  - tsconfigs
  - tseslint
  - tsup
  - Tuite
  - turborepo
  - typecheck
  - typeof
  - typesafe
  - unkey
  - uploadthing
  - vaul
  - viewports
  - WITA
